Repository web-standards-ru/web-standards.ru, pull requests merged in 2020-04, with the labels that each got.

#27 Правит ссылку на редактирование статьи
  src/layouts/article.njk
Labels: вёрстка

#23 Добавляет микроразметку Article на страницу статьи #4
  src/layouts/article.njk
Labels: вёрстка, улучшение

#22 Делает ленивую загрузку видео
  src/articles/parent-selector/images/hqdefault.jpg
  src/articles/parent-selector/index.md
  src/scripts/scripts.js
  src/styles/blocks/content.css
  src/styles/blocks/video.css
  src/styles/styles.css
Labels: вёрстка, скрипты, улучшение
